//! Official local UniFi Network Integration API connector.

mod client;
mod config;
mod connector;

pub use client::{UniFiNetworkClient, UniFiNetworkError};
pub use config::{config_schema, UniFiNetworkConfig};
pub use connector::{
    setup_guide, UniFiNetworkConnector, ACTION_AUTHORIZE_GUEST, ACTION_CREATE_VOUCHER,
    ACTION_CYCLE_POE, ACTION_RESTART, ACTION_REVOKE_VOUCHER, CAPABILITY_AUTHORIZE_GUEST,
    CAPABILITY_CREATE_VOUCHER, CAPABILITY_CYCLE_POE, CAPABILITY_READ_CLIENTS,
    CAPABILITY_READ_DEVICES, CAPABILITY_RESTART, CAPABILITY_REVOKE_VOUCHER,
    DATA_POINT_CLIENT_COUNT, DATA_POINT_CONNECTED_CLIENT_COUNT, DATA_POINT_CPU_UTILIZATION,
    DATA_POINT_DEVICE_COUNT, DATA_POINT_MEMORY_UTILIZATION, DATA_POINT_MODEL,
    DATA_POINT_ONLINE_DEVICE_COUNT, DATA_POINT_RADIOS, DATA_POINT_STATE, DATA_POINT_UPLINK_RX_RATE,
    DATA_POINT_UPLINK_TX_RATE, DATA_POINT_UPTIME, DISPLAY_NAME, ICON, RESOURCE_KIND_CLIENTS,
    RESOURCE_KIND_PORTS, RESOURCE_KIND_VOUCHERS, TYPE_ID,
};
