//! Official local UniFi Network Integration API connector.

mod client;
mod config;
mod connector;

pub use client::{UniFiNetworkClient, UniFiNetworkError};
pub use config::{config_schema, UniFiNetworkConfig};
pub use connector::{
    setup_guide, UniFiNetworkConnector, ACTION_ADOPT, ACTION_AUTHORIZE_GUEST,
    ACTION_CREATE_A_RECORD, ACTION_CREATE_CNAME_RECORD, ACTION_CREATE_FIREWALL_ZONE,
    ACTION_CREATE_FORWARD_DOMAIN, ACTION_CREATE_VOUCHER, ACTION_CYCLE_POE, ACTION_DELETE_ACL_RULE,
    ACTION_DELETE_DNS_POLICY, ACTION_DELETE_FIREWALL_POLICY, ACTION_DELETE_FIREWALL_ZONE,
    ACTION_DELETE_NETWORK, ACTION_RESTART, ACTION_REVOKE_VOUCHER, ACTION_TOGGLE_FIREWALL_LOGGING,
    ACTION_TOGGLE_WLAN_ENABLED, ACTION_UNAUTHORIZE_GUEST, CAPABILITY_ADOPT,
    CAPABILITY_AUTHORIZE_GUEST, CAPABILITY_CREATE_VOUCHER, CAPABILITY_CYCLE_POE,
    CAPABILITY_READ_CLIENTS, CAPABILITY_READ_DEVICES, CAPABILITY_RESTART,
    CAPABILITY_REVOKE_VOUCHER, CAPABILITY_UNAUTHORIZE_GUEST, DATA_POINT_CLIENT_COUNT,
    DATA_POINT_CONNECTED_CLIENT_COUNT, DATA_POINT_CPU_UTILIZATION, DATA_POINT_DEVICE_COUNT,
    DATA_POINT_LAST_HEARTBEAT_AT, DATA_POINT_LOAD_AVERAGE_15M, DATA_POINT_LOAD_AVERAGE_1M,
    DATA_POINT_LOAD_AVERAGE_5M, DATA_POINT_MEMORY_UTILIZATION, DATA_POINT_MODEL,
    DATA_POINT_ONLINE_DEVICE_COUNT, DATA_POINT_RADIOS, DATA_POINT_RADIO_TX_RETRY_PERCENT,
    DATA_POINT_STATE, DATA_POINT_UPLINK_RX_RATE, DATA_POINT_UPLINK_TX_RATE, DATA_POINT_UPTIME,
    DATA_POINT_WAN_COUNT, DISPLAY_NAME, ICON, RESOURCE_KIND_ACL_RULES, RESOURCE_KIND_CLIENTS,
    RESOURCE_KIND_DNS_POLICIES, RESOURCE_KIND_FIREWALL_POLICIES, RESOURCE_KIND_FIREWALL_ZONES,
    RESOURCE_KIND_NETWORKS, RESOURCE_KIND_PENDING_DEVICES, RESOURCE_KIND_PORTS,
    RESOURCE_KIND_SITE_TO_SITE_TUNNELS, RESOURCE_KIND_VOUCHERS, RESOURCE_KIND_VPN_SERVERS,
    RESOURCE_KIND_WANS, RESOURCE_KIND_WLAN_BROADCASTS, TYPE_ID,
};
