//! Pi-hole v6 REST connector: authenticated statistics and DNS blocking control.

mod client;
mod config;
mod connector;

pub use client::{PiHoleClient, PiHoleError};
pub use config::{config_schema, PiHoleConnectorConfig};
pub use connector::{
    setup_guide, PiHoleConnector, ACTION_ADD_DOMAIN, ACTION_REMOVE_DOMAIN, ACTION_SET_BLOCKING,
    ACTION_TOGGLE_DOMAIN_ENABLED, CAPABILITY_ADD_DOMAIN, CAPABILITY_READ_CLIENTS,
    CAPABILITY_READ_DOMAINS, CAPABILITY_READ_STATS, CAPABILITY_REMOVE_DOMAIN,
    CAPABILITY_SET_BLOCKING, CAPABILITY_TOGGLE_DOMAIN_ENABLED, DATA_POINT_BLOCKING_ENABLED,
    DATA_POINT_BLOCK_PERCENTAGE, DATA_POINT_DOMAINS_ON_BLOCKLIST, DATA_POINT_QUERIES_BLOCKED_TODAY,
    DATA_POINT_QUERIES_HISTORY, DATA_POINT_QUERIES_TODAY, DATA_POINT_UNIQUE_CLIENTS, DISPLAY_NAME,
    ICON, RESOURCE_KIND_CLIENTS, RESOURCE_KIND_DOMAINS, TYPE_ID,
};
