import {
  IconAccessPoint,
  IconActivity,
  IconActivityHeartbeat,
  IconAdjustments,
  IconAlertTriangle,
  IconAntenna,
  IconApi,
  IconArchive,
  IconBatteryCharging,
  IconBell,
  IconBluetooth,
  IconBolt,
  IconBox,
  IconBroadcast,
  IconBug,
  IconBulb,
  IconCalendar,
  IconCamera,
  IconChartBar,
  IconChartLine,
  IconClock,
  IconCloud,
  IconCloudComputing,
  IconCode,
  IconContainer,
  IconCpu,
  IconCpu2,
  IconDashboard,
  IconDatabase,
  IconDatabaseCog,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDisc,
  IconDownload,
  IconDroplet,
  IconFiles,
  IconFingerprint,
  IconFolder,
  IconFolderOpen,
  IconGauge,
  IconGitBranch,
  IconHeadphones,
  IconHeartbeat,
  IconHome,
  IconKey,
  IconLink,
  IconLock,
  IconMail,
  IconMessage,
  IconMicrophone,
  IconMovie,
  IconMusic,
  IconNetwork,
  IconPackage,
  IconPhoto,
  IconPlant,
  IconPlugConnected,
  IconPower,
  IconPrinter,
  IconRadar,
  IconRobot,
  IconRouter,
  IconRss,
  IconServer,
  IconServer2,
  IconServerBolt,
  IconServerCog,
  IconSettings,
  IconShield,
  IconShieldLock,
  IconSitemap,
  IconSmartHome,
  IconSun,
  IconTerminal2,
  IconThermometer,
  IconTool,
  IconTopologyStar3,
  IconUpload,
  IconUsb,
  IconUsers,
  IconVideo,
  IconWall,
  IconWebhook,
  IconWifi,
  IconWorld,
  IconWorldWww,
  type TablerIcon,
} from "@tabler/icons-react";

import type { TablerIconName } from "@loom/ui-kit/lib/icon-catalog";

/**
 * The curated Tabler components, keyed by catalog name.
 *
 * Only ever reached through a dynamic `import()` (see `icon-loaders.ts`), so the
 * whole subset is one lazily-loaded chunk that no screen pays for until it draws
 * a `tabler:` icon. Named imports from the package root rather than deep file
 * paths: the package publishes no `exports` map or per-icon type declarations,
 * but it is `sideEffects: false` with one ES module per icon, so the bundler
 * keeps exactly the icons named here and drops the other ~6000.
 *
 * One chunk for the set rather than one per icon: a Tabler icon is a few
 * hundred bytes of path data, and the picker draws all of them at once, so
 * per-icon chunks would be ninety requests to save a few kilobytes.
 *
 * Typed as `Record<TablerIconName, …>` so the catalog and this map cannot
 * disagree — an icon listed in one and not the other fails to compile.
 */
export const TABLER_COMPONENTS: Record<TablerIconName, TablerIcon> = {
  network: IconNetwork,
  router: IconRouter,
  wifi: IconWifi,
  "access-point": IconAccessPoint,
  antenna: IconAntenna,
  world: IconWorld,
  "world-www": IconWorldWww,
  sitemap: IconSitemap,
  "topology-star-3": IconTopologyStar3,
  "plug-connected": IconPlugConnected,
  bluetooth: IconBluetooth,
  rss: IconRss,
  database: IconDatabase,
  "database-cog": IconDatabaseCog,
  server: IconServer,
  "server-2": IconServer2,
  "server-cog": IconServerCog,
  "server-bolt": IconServerBolt,
  "device-floppy": IconDeviceFloppy,
  disc: IconDisc,
  folder: IconFolder,
  "folder-open": IconFolderOpen,
  archive: IconArchive,
  files: IconFiles,
  cloud: IconCloud,
  "cloud-computing": IconCloudComputing,
  download: IconDownload,
  upload: IconUpload,
  usb: IconUsb,
  cpu: IconCpu,
  "cpu-2": IconCpu2,
  "device-desktop": IconDeviceDesktop,
  "device-laptop": IconDeviceLaptop,
  "device-mobile": IconDeviceMobile,
  "device-tv": IconDeviceTv,
  "device-gamepad-2": IconDeviceGamepad2,
  printer: IconPrinter,
  container: IconContainer,
  box: IconBox,
  package: IconPackage,
  shield: IconShield,
  "shield-lock": IconShieldLock,
  lock: IconLock,
  key: IconKey,
  fingerprint: IconFingerprint,
  wall: IconWall,
  movie: IconMovie,
  video: IconVideo,
  music: IconMusic,
  photo: IconPhoto,
  headphones: IconHeadphones,
  microphone: IconMicrophone,
  camera: IconCamera,
  broadcast: IconBroadcast,
  home: IconHome,
  "smart-home": IconSmartHome,
  bulb: IconBulb,
  thermometer: IconThermometer,
  droplet: IconDroplet,
  sun: IconSun,
  plant: IconPlant,
  robot: IconRobot,
  bolt: IconBolt,
  "battery-charging": IconBatteryCharging,
  power: IconPower,
  activity: IconActivity,
  "activity-heartbeat": IconActivityHeartbeat,
  "chart-bar": IconChartBar,
  "chart-line": IconChartLine,
  gauge: IconGauge,
  dashboard: IconDashboard,
  heartbeat: IconHeartbeat,
  radar: IconRadar,
  "alert-triangle": IconAlertTriangle,
  bell: IconBell,
  clock: IconClock,
  "terminal-2": IconTerminal2,
  code: IconCode,
  api: IconApi,
  webhook: IconWebhook,
  "git-branch": IconGitBranch,
  bug: IconBug,
  settings: IconSettings,
  adjustments: IconAdjustments,
  tool: IconTool,
  mail: IconMail,
  message: IconMessage,
  users: IconUsers,
  link: IconLink,
  calendar: IconCalendar,
};
